image: Visual Studio 2017
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
install:
- ps: .\scripts\update-version.ps1
before_build:
- ps: dotnet restore
build_script:
- ps: dotnet build
test_script:
- ps: dotnet test Wkx.Tests
deploy:
- provider: NuGet
  api_key:
    secure: tGdmfvratYIxf1BjUhTaGbbbaSJjCq/G6c55mxgQQ5qUmu/Jfetzibf8uOKzqx9W
  on:
    appveyor_repo_tag: true
