image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: 1.0.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
install:
- ps: .\scripts\update-version.ps1
before_build:
- ps: nuget restore
build:
  project: Wkx.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
test:
  assemblies: '**\*.Tests.dll'
deploy:
- provider: NuGet
  api_key:
    secure: tGdmfvratYIxf1BjUhTaGbbbaSJjCq/G6c55mxgQQ5qUmu/Jfetzibf8uOKzqx9W
  on:
    appveyor_repo_tag: true
